apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "leanios-core.name" . }}-configmap
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "leanios-core.name" . }}
    chart: {{ template "leanios-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  APPSIGNAL_ACTIVE: '{{ .Values.environment.appsignal_active }}'
  APPSIGNAL_APP_ENV: '{{ .Values.environment.appsignal_app_env }}'
  APPSIGNAL_APP_NAME: '{{ .Values.environment.appsignal_app_name }}'
  APPSIGNAL_PUSH_API_KEY: '{{ .Values.environment.appsignal_push_api_key }}'
  CLOUDFLARE_MANAGE_DNS: '{{ .Values.environment.cloudflare_manage_dns }}'
  DATABASE_NAME: '{{ .Values.environment.database_name }}'
  DATABASE_PORT: '{{ .Values.environment.database_port }}'
  DATABASE_SSL_MODE: '{{ .Values.environment.database_ssl_mode }}'
  DATABASE_USER: '{{ .Values.environment.database_user }}'
  DELAYED_JOB_DEFAULT_QUEUE: '{{ .Values.environment.delayed_job_default_queue }}'
  DELAYED_JOB_MAX_PRIORITY: '{{ .Values.environment.delayed_job_max_priority }}'
  DELAYED_JOB_MIN_PRIORITY: '{{ .Values.environment.delayed_job_min_priority }}'
  DELAYED_JOB_QUIET: '{{ .Values.environment.delayed_job_quiet }}'
  DELAYED_JOB_READ_AHEAD: '{{ .Values.environment.delayed_job_read_ahead }}'
  DELAYED_JOB_SLEEP_DELAY: '{{ .Values.environment.delayed_job_sleep_delay }}'
  DELAYED_JOB_WORKER_QUEUES: '{{ .Values.environment.delayed_job_worker_queues }}'
  DEVISE_LOCKABLE_ENABLED: '{{ .Values.environment.devise_lockable_enabled }}'
  DEVISE_MAILER_SENDER: '{{ .Values.environment.devise_mailer_sender }}'
  EXCLUDED_SUBDOMAIN: '{{ .Values.environment.excluded_subdomain }}'
  HOST_NAME: '{{ .Values.environment.host_name }}'
  LOG_LEVEL: '{{ .Values.environment.log_level }}'
  SLACK_CHANNEL: '{{ .Values.environment.slack_channel }}'
  SLACK_ENABLED: '{{ .Values.environment.slack_enabled }}'
  SMTP_SERVER_AUTHENTICATION: '{{ .Values.environment.smtp_server_authentication }}'
  SMTP_SERVER_DOMAIN: '{{ .Values.environment.smtp_server_domain }}'
  SMTP_SERVER_ENABLE_STARTTLS_AUTO: '{{ .Values.environment.smtp_server_enable_starttls_auto }}'
  SMTP_SERVER_PORT: '{{ .Values.environment.smtp_server_port }}'
  SMTP_SERVER_USER_NAME: '{{ .Values.environment.smtp_server_user_name }}'
  STORAGE_BUCKET: '{{ .Values.environment.storage_bucket }}'
  STORAGE_REGION: '{{ .Values.environment.storage_region }}'
  STORAGE_SERVICE: '{{ .Values.environment.storage_service }}'
  TRACKING_ENABLED: '{{ .Values.environment.tracking_enabled }}'
