{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leanios-core.name" . }}-secrets
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "leanios-core.name" . }}
    chart: {{ template "leanios-core.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  CLOUDFLARE_DNS_TOKEN: {{ .Values.environment.cloudflare_dns_token  | b64enc | quote }}
  CLOUDFLARE_DESTINATION_IP: {{ .Values.environment.cloudflare_destination_ip  | b64enc | quote }}
  CLOUDFLARE_ZONE_ID: {{ .Values.environment.cloudflare_zone_id  | b64enc | quote }}
  DATABASE_HOST: {{ .Values.environment.database_host | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.environment.database_password | b64enc | quote }}
  GOOGLE_RECAPTCHA_SECRET_KEY: {{ .Values.environment.google_recaptcha_secret_key | b64enc | quote }}
  GOOGLE_RECAPTCHA_SITE_KEY: {{ .Values.environment.google_recaptcha_site_key | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.environment.secret_key_base | b64enc | quote }}
  SLACK_USERNAME: {{ .Values.environment.slack_username | b64enc | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.environment.slack_webhook_url | b64enc | quote }}
  SMTP_SERVER_ADDRESS: {{ .Values.environment.smtp_server_address | b64enc | quote }}
  SMTP_SERVER_PASSWORD: {{ .Values.environment.smtp_server_password | b64enc | quote }}
  STORAGE_ACCESS_KEY_ID: {{ .Values.environment.storage_access_key_id | b64enc | quote }}
  STORAGE_ENDPOINT: {{ .Values.environment.storage_endpoint | b64enc | quote }}
  STORAGE_SECRET_ACCESS_KEY: {{ .Values.environment.storage_secret_access_key | b64enc | quote }}
  HUBSPOT_PORTAL_ID: {{ .Values.environment.hubspot_portal_id | b64enc | quote }}
  HUBSPOT_FORM_ID: {{ .Values.environment.hubspot_form_id | b64enc | quote }}
  INFLUXDB_ORGANIZATION: {{ .Values.environment.influxdb_organization | b64enc | quote }}
  INFLUXDB_HOST: {{ .Values.environment.influxdb_host | b64enc | quote }}
  INFLUXDB_ADMIN_TOKEN: {{ .Values.environment.influxdb_admin_token | b64enc | quote }}
  REDIS_URL: {{ .Values.environment.redis_url | b64enc | quote }}
{{- end }}
