# Default values for banking-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

webReplicaCount: 1
djsReplicaCount: 1


image:
  repository: leanios/leanios-core
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - leanios.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecretName: leanios-core-docker-config
# existingSecret: name-of-existing-secret

environment:
  appsignal_active: 'false'
  appsignal_app_env: 'stage'
  appsignal_app_name: 'leanios-core'
  appsignal_push_api_key: 'changeme'
  database_name: 'changeme'
  database_port: 'changeme'
  database_ssl_mode: 'changeme'
  database_user: 'changeme'
  delayed_job_default_queue: 'default'
  delayed_job_max_priority: '100'
  delayed_job_min_priority: '10'
  delayed_job_quiet: 'true'
  delayed_job_read_ahead: '5'
  delayed_job_sleep_delay: '5'
  delayed_job_worker_queues: 'mailers,default,DEVISE_NOTIFICATION,DNS_MANAGMENT'
  devise_lockable_enabled: 'true'
  devise_mailer_sender: 'changeme'
  excluded_subdomain: ''
  host_name: 'changeme'
  log_level: 'debug'
  slack_channel: 'changeme'
  slack_enabled: 'false'
  smtp_server_authentication: 'plain'
  smtp_server_domain: 'changeme'
  smtp_server_enable_starttls_auto: 'changeme'
  smtp_server_port: 'changeme'
  smtp_server_user_name: 'changeme'
  storage_bucket: 'changeme'
  storage_region: 'changeme'
  storage_service: 'changeme'
  tracking_enabled: 'false'
  cloudflare_manage_dns: 'changeme'
  # Sensitive data that need to be stored and managed with helm secrets
  cloudflare_dns_token: 'changeme'
  cloudflare_destination_ip: 'changeme'
  cloudflare_zone_id: 'changeme'
  database_host: 'changeme'
  database_password: 'changeme'
  google_recaptcha_secret_key: 'changeme'
  google_recaptcha_site_key: 'changeme'
  secret_key_base: 'changeme'
  slack_username: 'changeme'
  slack_webhook_url: 'changeme'
  smtp_server_address: 'changeme'
  smtp_server_password: 'changeme'
  storage_access_key_id: 'changeme'
  storage_endpoint: 'changeme'
  storage_secret_access_key: 'changeme'
  hubspot_portal_id: 'changeme'
  hubspot_form_id: 'changeme'
  influxdb_organization: 'changeme'
  influxdb_host: 'changeme'
  influxdb_admin_token: 'changeme'
  redis_url: 'changeme'
